apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # to communicate with AWS
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    alb.ingress.kubernetes.io/group.order: '1'
  labels:
    {{ include "labels.reverseProxy" . | nindent 4 }}
  name: {{ include "release" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.apiDomain }}
      http:
        paths:
          - backend:
              service:
                name: "{{ include "release" . }}-reverse-proxy"
                port:
                  name: http
            pathType: ImplementationSpecific
