# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include "labels.reverseProxy" . | nindent 4 }}
  name: "{{ include "name" . }}-reverse-proxy"
  namespace: {{ .Release.Namespace }}
data:
  default.conf.template: |-
    {{ .Files.Get .Values.reverseProxy.nginxTemplateFile | nindent 4 }}
  404.html: |-
    {{ .Files.Get .Values.reverseProxy.error404File | nindent 4 }}
  openapi.json: |-
    {{ .Files.Get .Values.reverseProxy.openapiFile | nindent 4 }}
