{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{ include "labels" . | nindent 4 }}
  name: {{ include "release" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /prometheus
      port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "labels.api" . | nindent 6 }}
{{- end }}
