mongodb:
  enabled: true

storage:
  # JSON format is used because it's easier (ie. less error prone) to copy/paste the output of terraform
  nfs: {"path":"/fsx","server":"svm-0006d5ba595c33b3e.fs-079a245c1521ad9fe.fsx.us-east-1.amazonaws.com"}

api:
  replicas: 1

  ingress:
    annotations:
      # Link to Route53 - we could set any subdomain to us.dev.moon.huggingface.tech (common zone to the k8s cluster)
      external-dns.alpha.kubernetes.io/hostname: "datasets-server.us.dev.moon.huggingface.tech"
      alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80, \"HTTPS\": 443}]"
      alb.ingress.kubernetes.io/load-balancer-name: "hub-datasets-server-dev"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/tags: "Env=dev,Project=datasets-server,Terraform=true"
      kubernetes.io/ingress.class: "alb"

  resources:
    requests:
      cpu: 0.01
    limits:
      cpu: 1

datasets-worker:
  replicas: 2

  resources:
    requests:
      cpu: 0.01
    limits:
      cpu: 1

splits-worker:
  replicas: 5

  resources:
    requests:
      cpu: 0.01
    limits:
      cpu: 1
