apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "labels.api" . | nindent 4 }}
  name: "{{ .Release.Name }}-api"
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ include "labels.api" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{ include "labels.api" . | nindent 8 }}
    spec:
      initContainers:
        {{ include "initContainerAssets" . | nindent 8 }}
      containers:
        {{ include "containerApi" . | nindent 8 }}
      nodeSelector:
        {{ toYaml .Values.api.nodeSelector | nindent 8 }}
      tolerations:
        {{ toYaml .Values.api.tolerations | nindent 8 }}
      volumes:
      - name: nfs
        nfs:
          server: {{ .Values.storage.nfs.server }}
          path: {{ .Values.storage.nfs.path }}
      securityContext:
        runAsUser: {{ .Values.uid }}
        runAsGroup: {{ .Values.gid }}
        runAsNonRoot: true
