# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.
{{- if and .Values.cacheRefresh.enabled .Values.images.jobs.cacheRefresh }}
apiVersion: batch/v1
kind: Job
metadata:
  labels: {{ include "labels.cacheRefresh" . | nindent 4 }}
  name: "{{ include "name" . }}-job-cache-refresh"
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels: {{ include "labels.cacheRefresh" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- include "image.imagePullSecrets" . | nindent 6 }}
      containers: {{ include "containerCacheRefresh" . | nindent 8 }}
      nodeSelector: {{ toYaml .Values.cacheRefresh.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.cacheRefresh.tolerations | nindent 8 }}
      securityContext: {{ include "securityContext" . | nindent 8 }}
  backoffLimit: 0
{{- end }}
