[tool.poetry]
name = "admin-ui"
version = "0.1.0"
description = "Admin interface for datasets-server"
authors = ["Quentin Lhoest <quentin@huggingface.co>"]

[tool.poetry.dependencies]
gradio = "3.28.1"
matplotlib = "^3.7.0"
requests = "^2.28.2"
pygraphviz = "~1.10"
python = "~3.9.15"
huggingface-hub = "^0.14.1"
duckdb = "^0.6.1"
libcommon = { path = "../../libs/libcommon", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
