# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "labels.parquetAndDatasetInfo" . | nindent 4 }}
  name: "{{ include "name" . }}-worker-parquet-and-dataset-info"
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.parquetAndDatasetInfo.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{ include "labels.parquetAndDatasetInfo" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ include "labels.parquetAndDatasetInfo" . | nindent 8 }}
    spec:
      {{- include "image.imagePullSecrets" . | nindent 6 }}
      initContainers: {{ include "initContainerCache" . | nindent 8 }}
      containers: {{ include "containerWorkerParquetAndDatasetInfo" . | nindent 8 }}
      nodeSelector: {{ toYaml .Values.parquetAndDatasetInfo.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.parquetAndDatasetInfo.tolerations | nindent 8 }}
      volumes: {{ include "volumeData" . | nindent 8 }}
      securityContext: {{ include "securityContext" . | nindent 8 }}
