# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "labels.sizes" . | nindent 4 }}
  name: "{{ include "name" . }}-worker-sizes"
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.sizes.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{ include "labels.sizes" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ include "labels.sizes" . | nindent 8 }}
    spec:
      {{- include "image.imagePullSecrets" . | nindent 6 }}
      containers: {{ include "containerWorkerSizes" . | nindent 8 }}
      nodeSelector: {{ toYaml .Values.sizes.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.sizes.tolerations | nindent 8 }}
      securityContext: {{ include "securityContext" . | nindent 8 }}
