version: "3.9"
services:
  common:
    environment:
      # common
      COMMON_HF_ENDPOINT: ${COMMON_HF_ENDPOINT-https://huggingface.co}
      COMMON_HF_TOKEN: ${COMMON_HF_TOKEN-}
      COMMON_LOG_LEVEL: ${COMMON_LOG_LEVEL-INFO}
      COMMON_CONTENT_MAX_SIZE: ${COMMON_CONTENT_MAX_SIZE-1000000}
      # huggingface_hub
      HF_ENDPOINT: ${COMMON_HF_ENDPOINT-https://huggingface.co} # see https://github.com/huggingface/datasets/pull/5196#issuecomment-1322191411
      # cache
      CACHE_MONGO_URL: ${CACHE_MONGO_URL-mongodb://mongodb} # use mongo container by default
      CACHE_MONGO_DATABASE: ${CACHE_MONGO_DATABASE-datasets_server_cache}
      # queue
      QUEUE_MAX_JOBS_PER_NAMESPACE: ${QUEUE_MAX_JOBS_PER_NAMESPACE-1}
      QUEUE_MONGO_URL: ${QUEUE_MONGO_URL-mongodb://mongodb} # use mongo container by default
      QUEUE_MONGO_DATABASE: ${QUEUE_MONGO_DATABASE-datasets_server_queue}
      # worker
      WORKER_LOOP_MAX_DISK_USAGE_PCT: ${WORKER_LOOP_MAX_DISK_USAGE_PCT-90}
      WORKER_LOOP_MAX_LOAD_PCT: ${WORKER_LOOP_MAX_LOAD_PCT-70}
      WORKER_LOOP_MAX_MEMORY_PCT: ${WORKER_LOOP_MAX_MEMORY_PCT-80}
      WORKER_LOOP_SLEEP_SECONDS: ${WORKER_LOOP_SLEEP_SECONDS-15}
  datasets-worker:
    extends:
      service: common
    environment:
      # datasets
      DATASETS_BASED_HF_DATASETS_CACHE: ${HF_DATASETS_CACHE-/datasets-cache}
      HF_MODULES_CACHE: ${HF_DATASETS_CACHE-/modules-cache}
      NUMBA_CACHE_DIR: ${NUMBA_CACHE_DIR-/numba-cache}
