version: "3.9"
services:
  common:
    environment:
      # common
      COMMON_ASSETS_BASE_URL: "http://localhost:${PORT_REVERSE_PROXY-8000}/assets" # hard-coded to work with the reverse-proxy
      COMMON_HF_ENDPOINT: ${COMMON_HF_ENDPOINT-https://huggingface.co}
      COMMON_HF_TOKEN: ${COMMON_HF_TOKEN-}
      COMMON_LOG_LEVEL: ${COMMON_LOG_LEVEL-INFO}
      # huggingface_hub
      HF_ENDPOINT: ${COMMON_HF_ENDPOINT-https://huggingface.co} # see https://github.com/huggingface/datasets/pull/5196#issuecomment-1322191411
      # cache
      CACHE_MONGO_URL: ${CACHE_MONGO_URL-mongodb://mongodb} # use mongo container by default
      CACHE_MONGO_DATABASE: ${CACHE_MONGO_DATABASE-datasets_server_cache}
      # queue
      QUEUE_MAX_JOBS_PER_NAMESPACE: ${QUEUE_MAX_JOBS_PER_NAMESPACE-1}
      QUEUE_MONGO_URL: ${QUEUE_MONGO_URL-mongodb://mongodb} # use mongo container by default
      QUEUE_MONGO_DATABASE: ${QUEUE_MONGO_DATABASE-datasets_server_queue}
      # worker
      WORKER_MAX_LOAD_PCT: ${WORKER_MAX_LOAD_PCT-70}
      WORKER_MAX_MEMORY_PCT: ${WORKER_MAX_MEMORY_PCT-80}
      WORKER_SLEEP_SECONDS: ${WORKER_SLEEP_SECONDS-15}
  datasets-worker:
    extends:
      service: common
    environment:
      # datasets
      HF_DATASETS_CACHE: ${HF_DATASETS_CACHE-/datasets-cache}
      HF_MODULES_CACHE: ${HF_MODULES_CACHE-/modules-cache}
      NUMBA_CACHE_DIR: ${NUMBA_CACHE_DIR-/numba-cache}
