# name: "Build and push docker images"

# on:
#   workflow_dispatch:
#   push:

# env:
#   REGION: us-east-1
#   REPOSITORY_PREFIX: 707930574880.dkr.ecr.us-east-1.amazonaws.com/hub-datasets-server-

# jobs:
#   build-and-push-image-api:
#     strategy:
#       fail-fast: false
#       matrix:
#         service: [admin, api, worker]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Set outputs
#         id: vars
#         run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.REGION }}
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: ${{ env.REPOSITORY_PREFIX }}${{ matrix.service }}
#           tags: |
#             type=raw,value=sha-${{ steps.vars.outputs.sha_short }}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: services/${{ matrix.service }}/Dockerfile
#           build-args: COMMIT=${{ steps.vars.outputs.sha_short }}
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
#           # see https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
#           cache-from: type=gha,scope=buildkit-${{ matrix.service }}
#           cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.service }}
