# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

name: jobs/mongodb_migration
on:
  workflow_dispatch:
  push:
    paths:
      - 'jobs/mongodb_migration/**'
      - 'libs/libcommon/**'
      - '.github/workflows/j-mongodb_migration.yml'
      - '.github/workflows/_quality-python.yml'
      - '.github/workflows/_unit-tests-python.yml'
      - 'tools/docker-compose-mongo.yml'
  pull_request:
    paths:
      - 'jobs/mongodb_migration/**'
      - 'libs/libcommon/**'
      - '.github/workflows/j-mongodb_migration.yml'
      - '.github/workflows/_quality-python.yml'
      - '.github/workflows/_unit-tests-python.yml'
      - 'tools/docker-compose-mongo.yml'
jobs:
  quality:
    uses: ./.github/workflows/_quality-python.yml
    with:
      working-directory: jobs/mongodb_migration
  unit-tests:
    uses: ./.github/workflows/_unit-tests-python.yml
    with:
      working-directory: jobs/mongodb_migration
