name: services/admin
on:
  workflow_dispatch:
  push:
    paths:
      - 'services/admin/**'
env:
  service: admin
  working-directory: services/admin
jobs:
  quality:
    uses: ./.github/workflows/_quality-python.yml
    with:
      working-directory: ${{ env.working-directory }}
  unit-tests:
    uses: ./.github/workflows/_unit-tests-python.yml
    with:
      working-directory: ${{ env.working-directory }}
  docker:
    uses: ./.github/workflows/_docker.yml
    with:
      service: ${{ env.service }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
