# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

name: workers/datasets_based
on:
  workflow_dispatch:
  push:
    paths:
      - 'libs/libcommon/**'
      - 'workers/datasets_based/Dockerfile'
      - 'workers/datasets_based/src/**'
      - 'workers/datasets_based/poetry.lock'
      - 'workers/datasets_based/pyproject.toml'
      - '.github/workflows/w-datasets_based-build-docker.yml'
      - '.github/workflows/_build_push_docker_hub.yml'
      - 'vendors/'
  pull_request:
    paths:
      - 'libs/libcommon/**'
      - 'workers/datasets_based/Dockerfile'
      - 'workers/datasets_based/src/**'
      - 'workers/datasets_based/poetry.lock'
      - 'workers/datasets_based/pyproject.toml'
      - '.github/workflows/w-datasets_based-build-docker.yml'
      - '.github/workflows/_build_push_docker_hub.yml'
      - 'vendors/'
jobs:
  docker:
    uses: ./.github/workflows/_build_push_docker_hub.yml
    with:
      directory: workers
      project: datasets_based
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
