# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The HuggingFace Authors.

name: workers/splits
on:
  workflow_dispatch:
  push:
    paths:
      - 'workers/splits/**'
      - '.github/workflows/w-splits.yml'
      - '.github/workflows/_quality-python.yml'
      - '.github/workflows/_unit-tests-python.yml'
      - 'tools/docker-compose-mongo.yml'
      - 'vendors/'
jobs:
  quality:
    uses: ./.github/workflows/_quality-python.yml
    with:
      working-directory: workers/splits
      safety-exceptions: ""
      is-datasets-worker: true
  unit-tests:
    uses: ./.github/workflows/_unit-tests-python.yml
    with:
      working-directory: workers/splits
      is-datasets-worker: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
