apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "labels.splitsWorker" . | nindent 4 }}
  name: "{{ .Release.Name }}-splits-worker"
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.splitsWorker.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ include "labels.splitsWorker" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{ include "labels.splitsWorker" . | nindent 8 }}
    spec:
      initContainers:
        {{ include "initContainerAssets" . | nindent 8 }}
        {{ include "initContainerCache" . | nindent 8 }}
      containers:
        {{ include "containerSplitsWorker" . | nindent 8 }}
      nodeSelector:
        {{ toYaml .Values.splitsWorker.nodeSelector | nindent 8 }}
      tolerations:
        {{ toYaml .Values.splitsWorker.tolerations | nindent 8 }}
      volumes:
        - name: nfs
          nfs:
            server: {{ .Values.storage.nfs.server }}
            path: {{ .Values.storage.nfs.path }}
      securityContext:
        runAsUser: {{ .Values.uid }}
        runAsGroup: {{ .Values.gid }}
        runAsNonRoot: true
